#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
c=1
while [ $c -le 10 ]; do
    if [ $c -eq 9 ]
    then
	echo "Best School"
	echo "Hi"
    else
        echo "Best School"
    fi
    ((c++))
done
