#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for file in *
do
    if [ -f "$file" ]; then
        if [[ $file == *-* ]]; then
	    display_name=$(echo "$file" | cut -d'-' -f2-)
	    echo "$display_name"
        else
	    echo "$file"
	fi
    fi
done
